# Generated by Django 5.1.3 on 2024-11-24 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_transacao_data_alter_transacao_observacoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
